# Generated by Django 3.0.2 on 2020-01-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napominalka', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='napominalka.Tag'),
        ),
    ]
